[package]
name = "json-rpc-client"
version = "0.1.0"
edition = "2021"
authors = ["Russell Wong"]

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
thiserror = "1.0"

reqwest = { version = "0.11.9", features = ["json"] }
